// Mocks generated by Mockito 5.4.6 from annotations
// in exemplo/test/data/repositories/pessoa_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:exemplo/data/datasources/pessoa_local_datasource.dart' as _i2;
import 'package:exemplo/data/models/pessoa_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PessoaLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPessoaLocalDataSource extends _i1.Mock
    implements _i2.PessoaLocalDataSource {
  MockPessoaLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insertPessoa(_i4.PessoaModel? pessoa) =>
      (super.noSuchMethod(
            Invocation.method(#insertPessoa, [pessoa]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<_i4.PessoaModel?> getPessoaById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPessoaById, [id]),
            returnValue: _i3.Future<_i4.PessoaModel?>.value(),
          )
          as _i3.Future<_i4.PessoaModel?>);

  @override
  _i3.Future<List<_i4.PessoaModel>> getAllPessoas() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPessoas, []),
            returnValue: _i3.Future<List<_i4.PessoaModel>>.value(
              <_i4.PessoaModel>[],
            ),
          )
          as _i3.Future<List<_i4.PessoaModel>>);

  @override
  _i3.Future<int> updatePessoa(_i4.PessoaModel? pessoa) =>
      (super.noSuchMethod(
            Invocation.method(#updatePessoa, [pessoa]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> deletePessoa(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePessoa, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
